### ISSUE TITLE
capture still launch after [capture stop] ?

### ISSUE THREAD

**Issue by lawreytjh** [TheLevelUp/ZXingObjC#200]
I tried to force stop it after first detection of the QR code as i need to push a new controller in, but the detection runs a few times and hence pushed multiple controllers, I tried putting a capture stop right after the vibration but it still happens multiple calls. any idea why?

**Comment by cwalcott** [comment]
Should be fixed as of ca9e713

**Comment by GrenderG** [comment]
Hi, i'm getting the same error. It seems not fixed. What can I do?

**Comment by FrankKair** [comment]
Hi, I've updated the library to the current version (which btw, it's not the one on the readme file!) and I'm getting the same error (pushing multiple view controllers due to the detection).

@lawreytjh @cwalcott @GrenderG

**Comment by mattdouhan** [comment]
This is happening again on iOS 11 and current version

**Comment by ethan-gerardot** [comment]
So is this ever gonna get fixed? This and 328 are closed even though I don't see a fix. Am I missing something?
