### ISSUE TITLE
Decode multiple barcodes doesn't work in Swift

### ISSUE THREAD

**Issue by KlimczakM** [TheLevelUp/ZXingObjC#299]
I use 3.1 version (via CocoaPods) and this code:

```
let source = ZXCGImageLuminanceSource(CGImage: image.CGImage)
        let binarizer = ZXHybridBinarizer.binarizerWithSource(source!) as! ZXBinarizer
        let bitmap = ZXBinaryBitmap.binaryBitmapWithBinarizer(binarizer) as! ZXBinaryBitmap
        let hints = ZXDecodeHints.hints() as! ZXDecodeHints
        hints.tryHarder = true
        let reader = ZXMultiFormatReader.reader() as! ZXReader
        let multi = ZXGenericMultipleBarcodeReader(delegate: reader)
        do {
            let result = try multi!.decodeMultiple(bitmap, hints: hints)
            print(result)
        } catch _ {
            print("Not found!")
        }
```

It never finds any QR code. I've tried decoding single code and multiple codes on black/white background in many variants. It's not only my problem: https://github.com/TheLevelUp/ZXingObjC/pull/235#issuecomment-224800185

**Comment by benjohnde** [comment]
Fixed, thanks to @schoosch !

**Comment by himanshupadia** [comment]
@KlimczakM @benjohnde Could you please help me, Below is my updated swift code.
**It's not working for multiple barcode reading, every time is print "Not found!".**
I have update ZXingObjC pod and swift 4. 
Single barcode is working fine but multiple not found.
```
let source = ZXCGImageLuminanceSource(cgImage: tempImage.cgImage)
let bitmap = ZXBinaryBitmap(binarizer: ZXHybridBinarizer(source: source))
let hints = ZXDecodeHints()
hints.tryHarder = true
let reader = ZXMultiFormatReader()
let multiReader = ZXGenericMultipleBarcodeReader(delegate: reader)
do {
    let result = try multiReader!.decodeMultiple(bitmap, hints: hints)
    print(result)
} catch _ {
    print("Not found!")
}
```
Any help would we appreciated.
Thanks in advance.

**Comment by neacao** [comment]
Seems like 3.3.0 still having this issue. I could not decode any QR code by using ZXingObjC but Vision can.
ps: the code same as @himanshupadia post above

**Comment by benjohnde** [comment]
Could you upload example barcodes you tried to scan? I am going to test this issue tomorrow.

**Comment by neacao** [comment]
I think i have figured out what wrong, seems like ZXQRCodeDetector return too many useless finder pattern infos i.e points, just hooked into ZXQRCodeFinderPatternFinder to detect & draw the finder points. 
So if we tested by capture an image & run the decode, it might return nothing (Vision can), but using live camera is good for this example (BarcodeScanner)
cc @himanshupadia , did I answer your problem ?
-----
@benjohnde can we optimize anything of ZXQRCodeDetector to limit the useless finder pattern. What i'm trying to do is pre-processing the input image, so we can force camera quick focus to the QR code, just same as what WeChat did.
Btw,Thanks for your quick response 👍

**Comment by benjohnde** [comment]
@neacao I am going to port the most recent changes from zxing/zxing to this port. I cannot say how long it will take. But after that, I would deep dive into this issue. Maybe it is now the time to start porting changes back to this project :) I believe those problems are probably fixed in the official zxing project.

**Comment by neacao** [comment]
Can you give some key points that i can help to take look inside official project and support to port it into this repo ? :D

**Comment by benjohnde** [comment]
Yeah sure: I am basically looking for new commits, regarding the core of zxing, in the official repository zxing/zxing and porting those commits to ZXingObjC.

That is an on-going task and will never be finished, but beforehand I am going to deep dive into most of the current issues. I believe it makes more sense to fix bugs which are already solved in the origin.

**Comment by benjohnde** [comment]
https://github.com/TheLevelUp/ZXingObjC/issues/348

**Comment by benjohnde** [comment]
I already started to port commits. Best approach is to use some helper which draws the full graph and looking for changes specific to `core/`.

**Comment by benjohnde** [comment]
I am looking forward to fix most of the bugs and port all outstanding commits from zxing/zxing (as of now) until December '18. Then the job is mostly cleaning up and writing some sophisticated Swift examples.

**Comment by neacao** [comment]
You did great work 👍 . I will take a look on current issues to see what i can support to resolve :D

**Comment by benjohnde** [comment]
Should be solved with the current upstream ports. Maybe try `pureBarcode = YES;` in `ZXDecodeHints`.
